//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infotepAssistControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia_facilitador
    {
        public int id_asis_facilitador { get; set; }
        public string cedula_facilitador { get; set; }
        public string codigo_materia { get; set; }
        public string hora_llegada { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora_salida { get; set; }
    }
}
