//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infotepAssistControl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class infotedbEntities : DbContext
    {
        public infotedbEntities()
            : base("name=infotedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asistencia_facilitador> asistencia_facilitador { get; set; }
        public virtual DbSet<asistencia_participante> asistencia_participante { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<correos> correos { get; set; }
    
        public virtual ObjectResult<Rango_Fecha_Facilitador_Result> Rango_Fecha_Facilitador(Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2)
        {
            var fecha1Parameter = fecha1.HasValue ?
                new ObjectParameter("Fecha1", fecha1) :
                new ObjectParameter("Fecha1", typeof(System.DateTime));
    
            var fecha2Parameter = fecha2.HasValue ?
                new ObjectParameter("Fecha2", fecha2) :
                new ObjectParameter("Fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rango_Fecha_Facilitador_Result>("Rango_Fecha_Facilitador", fecha1Parameter, fecha2Parameter);
        }
    
        public virtual ObjectResult<Rango_Fecha_Participante_Result> Rango_Fecha_Participante(Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2)
        {
            var fecha1Parameter = fecha1.HasValue ?
                new ObjectParameter("Fecha1", fecha1) :
                new ObjectParameter("Fecha1", typeof(System.DateTime));
    
            var fecha2Parameter = fecha2.HasValue ?
                new ObjectParameter("Fecha2", fecha2) :
                new ObjectParameter("Fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rango_Fecha_Participante_Result>("Rango_Fecha_Participante", fecha1Parameter, fecha2Parameter);
        }
    }
}
